{% set name = "apeye-core" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apeye_core-{{ version }}.tar.gz
  sha256: b57953dbd13d6e6c6228281bbf4468b98bd21261f1b23812bfab811f247edc0a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatch-requirements-txt
    - pip
    - python >=3.6
  run:
    - domdf-python-tools >=2.6.0
    - idna >=2.5
    - python >=3.6

test:
  imports:
    - apeye_core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/apeye-core/
  summary: Core (offline) functionality for the apeye library.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - domdfcoding
